### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by JaniniRami** [AcrobaticPanicc/Spotify-Playlist-Generator1#2]
Hey, I saw a lot of people including me getting an Internal Server Error, After I ran the flask app on my machine I figured out that this is caused by this line:
```
url_args =  "&".join([f"{key}={quote(val)}" for key, val in auth_query_parameters.items()])
``` 
The problem is clearly caused by quote(val) as  urllib.parse.quote only accepts strings and it getting bytes for some reason, a quick fix for that is using a simple str(val) like this: 
```
url_args ="&".join([f"{key}={quote(str(val))}" for key, val in auth_query_parameters.items()])
```
But now I am getting another error while trying to login to my spotify account:
```
INVALID_CLIENT: Invalid client
```
Any idea what is causing this error?

**Comment by AcrobaticPanicc** [comment]
Hi, 

Thanks! 

I just committed the change and I will push it later on today and would love it if you can tell me if it is working fine for you.
The reason

**Comment by AcrobaticPanicc** [comment]
Hi,

Thanks. I just committed the change and I will push it later on today and would love it if you can tell me if it is working.

The reason why you see the client error, is because you don't have the credentials (key and client secret) for my app. 

Thanks!

**Comment by JaniniRami** [comment]
Yeah I figured that was the problem, I will test it when its out nice work!

**Comment by AcrobaticPanicc** [comment]
Hi, please try now and let me know if it worked, thank you!

**Comment by JaniniRami** [comment]
Same thing, "Internal Server Error", Ill take a look at it sometime today to see what is causing it hoping it will help!

**Comment by AcrobaticPanicc** [comment]
I think it fixed. Apparently, some Spotify users don't have a display name and it returned a key error.
Please try now and let me know how it went.

**Comment by JaniniRami** [comment]
Still not working :( , I am also using a display name so I dont think its caused by that.
